version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: >-
    cd Core\Prism.Validation

    dotnet restore

    dotnet build -c Release

    cd ..\..